name:                termina
version:             0.1.0.0
github:              "termina-lang/transpiler"
license:             BSD3
author:              "Termina Language Group"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.org
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/termina#readme>

dependencies:
- base >= 4.7 && < 5
# Parser
- parsec
# Pretty printer lib
- prettyprinter
- prettyprinter-ansi-terminal
# Commandline options
- options
# REPL
- haskeline
# FilePath
- filepath
- text
- directory
- containers
- mtl
# Error messages pretty printer
- errata
- optparse-applicative
- yaml
- lens
- lsp

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -freverse-errors
# - -Wmissing-export-lists

default-extensions:
- LambdaCase
- TupleSections

library:
  source-dirs: src

executables:
  termina:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - termina

tests:
  termina-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - termina
    - hspec
    - hspec-discover
    - hspec-contrib
