module Semantic.Negative.CodeSpec (spec) where

import Pipeline.Common (compileErrorCode, compileProjectErrorCode)

import Test.Hspec
import Data.Text (pack)
import Data.List (sort, isPrefixOf, isSuffixOf)
import Control.Monad (forM_, forM)
import System.Directory (listDirectory)
import System.FilePath ((</>), dropExtension)

-- | Directory holding the negative semantic fixtures, relative to the package
-- root. Each file is named after the error code it must trigger, e.g.
-- @SE-016.fin@ must make the whole pipeline stop at the type checker with
-- error code @SE-016@.
fixturesDir :: FilePath
fixturesDir = "test" </> "Semantic" </> "fixtures"

-- | Directory holding the multi-module negative fixtures. Each subdirectory is
-- named after the error code it must trigger and contains one @.fin@ per module
-- (the file name is the module name). They exercise errors that only arise
-- across modules, e.g. referencing a type or function from a module that is not
-- imported (SE-199, SE-200).
multiDir :: FilePath
multiDir = "test" </> "Semantic" </> "fixtures-multi"

-- | Fixtures whose intended error is currently shadowed by an earlier-firing
-- check, so the program stops with a different code than its file name. They
-- are reported as pending (not failures) until the fixture is restructured to
-- isolate the intended error. The second component is the code produced today.
shadowed :: [(String, String)]
shadowed = []

-- | Human-readable title per error code (mirrors @errorTitle@ in
-- @Semantic.Errors@) so the test names read like the other negative specs:
-- @SE-NNN: <title>@.
titles :: [(String, String)]
titles =
  [ ("SE-001", "invalid array indexing")
  , ("SE-002", "object not found")
  , ("SE-003", "expected constant expression")
  , ("SE-004", "assignment to immutable variable")
  , ("SE-005", "missing else clause")
  , ("SE-006", "invalid cast")
  , ("SE-007", "invalid parameter type")
  , ("SE-008", "invalid return type")
  , ("SE-009", "extra arguments in procedure call")
  , ("SE-010", "missing arguments in procedure call")
  , ("SE-011", "argument type mismatch in procedure call")
  , ("SE-012", "unknown procedure")
  , ("SE-013", "resource class does not provide any interface")
  , ("SE-014", "resource class defines an action")
  , ("SE-015", "resource class defines an in port")
  , ("SE-016", "resource class defines an out port")
  , ("SE-017", "interface not found")
  , ("SE-018", "identifier not an interface")
  , ("SE-019", "procedure not from provided interfaces")
  , ("SE-020", "missing procedure")
  , ("SE-021", "extra parameters in procedure definition")
  , ("SE-022", "missing parameters in procedure definition")
  , ("SE-023", "parameter type mismatch in procedure definition")
  , ("SE-024", "task class provides an interface")
  , ("SE-025", "task class defines a procedure")
  , ("SE-026", "task class does not define any actions")
  , ("SE-027", "handler class provides an interface")
  , ("SE-028", "handler class defines a procedure")
  , ("SE-029", "handler class does not define any actions")
  , ("SE-030", "handler class defines multiple actions")
  , ("SE-031", "handler class does not define any sink port")
  , ("SE-032", "handler class defines multiple sink ports")
  , ("SE-033", "handler class defines an in port")
  , ("SE-034", "if-else-if condition not boolean")
  , ("SE-035", "extra arguments in function call")
  , ("SE-036", "missing arguments in function call")
  , ("SE-037", "argument type mismatch in function call")
  , ("SE-038", "access to a member that is not a function")
  , ("SE-039", "mutable reference to immutable object")
  , ("SE-040", "mutable reference to private object")
  , ("SE-041", "binary operation expected type on the left")
  , ("SE-042", "binary operation expected type on the right")
  , ("SE-043", "binary operation type mismatch")
  , ("SE-044", "binary operation expected result type not boolean")
  , ("SE-045", "binary operation expected boolean type on the left")
  , ("SE-046", "binary operation expected boolean type on the right")
  , ("SE-047", "binary operation expected result type not arithmetic")
  , ("SE-048", "binary operation expected arithmetic type on the left")
  , ("SE-049", "binary operation expected arithmetic type on the right")
  , ("SE-050", "binary operation expected positive numeric type on the right")
  , ("SE-051", "binary operation expected equatable type on the left")
  , ("SE-052", "binary operation expected equatable type on the right")
  , ("SE-053", "invalid type for the atomic access interface")
  , ("SE-054", "invalid type for the atomic array access interface")
  , ("SE-055", "invalid atomic type")
  , ("SE-056", "invalid atomic array type")
  , ("SE-057", "atomic connection type mismatch")
  , ("SE-058", "atomic array connection type mismatch")
  , ("SE-059", "unnecessary default case")
  , ("SE-060", "constant without known type")
  , ("SE-061", "invalid use of struct initializer")
  , ("SE-062", "struct initializer type mismatch")
  , ("SE-063", "enum initializer expected type mismatch")
  , ("SE-064", "invalid use of slice")
  , ("SE-065", "invalid use of an array initializer")
  , ("SE-066", "assignment of an array initializer to a non-array type")
  , ("SE-067", "invalid use of an expression list array initializer")
  , ("SE-068", "assignment of an array expression list initializer to a non-array type")
  , ("SE-069", "invalid use of an builtin variant initializer")
  , ("SE-070", "for loop lower bound type mismatch")
  , ("SE-071", "for loop upper bound type mismatch")
  , ("SE-072", "list of initializing expressions type mismatch")
  , ("SE-073", "expected return value")
  , ("SE-074", "return value not expected")
  , ("SE-075", "invalid array type")
  , ("SE-076", "invalid box type")
  , ("SE-077", "no type found")
  , ("SE-078", "global object but not a type")
  , ("SE-079", "invalid access to global object")
  , ("SE-080", "invalid write to a constant")
  , ("SE-081", "symbol already defined")
  , ("SE-082", "invalid expression in continue statement")
  , ("SE-083", "invalid method or viewer call in continue statement")
  , ("SE-084", "invalid member call in continue statement")
  , ("SE-085", "extra arguments in continuation action")
  , ("SE-086", "missing arguments in continuation action")
  , ("SE-087", "invalid use of an enum variant initializer")
  , ("SE-088", "enum variant not found")
  , ("SE-089", "extra parameters in enum variant")
  , ("SE-090", "missing parameters in enum variant")
  , ("SE-091", "enum variant parameter type mismatch")
  , ("SE-092", "function not found")
  , ("SE-093", "global object but not a function")
  , ("SE-094", "unexpected numeric constant")
  , ("SE-095", "invalid assignment expression type")
  , ("SE-096", "invalid message type")
  , ("SE-097", "invalid option type")
  , ("SE-098", "invalid reference type")
  , ("SE-099", "invalid fixed-location type")
  , ("SE-100", "invalid allocator type")
  , ("SE-101", "invalid class field type")
  , ("SE-102", "invalid struct field type")
  , ("SE-103", "invalid enum parameter type")
  , ("SE-104", "invalid access port type")
  , ("SE-105", "invalid declaration type")
  , ("SE-106", "invalid type specifier")
  , ("SE-107", "invalid numeric constant type")
  , ("SE-108", "invalid action parameter type")
  , ("SE-109", "invalid procedure parameter type")
  , ("SE-110", "extra arguments in member function call")
  , ("SE-111", "missing arguments in member function call")
  , ("SE-112", "member function call argument type mismatch")
  , ("SE-113", "invalid array index type")
  , ("SE-114", "invalid array slice lower bound type")
  , ("SE-115", "invalid array slice upper bound type")
  , ("SE-116", "invalid number of arguments in outbound port send")
  , ("SE-117", "output port argument type mismatch")
  , ("SE-118", "assignment expression type mismatch")
  , ("SE-119", "missing field/s in field assignment expression")
  , ("SE-120", "unknown field/s in field assignment expression")
  , ("SE-121", "field is not a fixed-location field")
  , ("SE-122", "field is not an access port field")
  , ("SE-123", "field is not a sink or inbound port field")
  , ("SE-124", "field is not an outbound port field")
  , ("SE-125", "invalid member access type")
  , ("SE-126", "invalid member function call type")
  , ("SE-127", "unknown field in member access")
  , ("SE-128", "invalid procedure call inside member function")
  , ("SE-129", "constant out of range")
  , ("SE-130", "invalid type for for-loop iterator")
  , ("SE-131", "type name already used")
  , ("SE-132", "global name already used")
  , ("SE-133", "function name already used")
  , ("SE-134", "invalid global object in access port connection")
  , ("SE-135", "resource does not provide the interface")
  , ("SE-136", "invalid sink port connection")
  , ("SE-137", "invalid inbound port connection")
  , ("SE-138", "invalid outbound port connection")
  , ("SE-139", "invalid allocator port connection")
  , ("SE-140", "invalid atomic access port connection")
  , ("SE-141", "invalid atomic array access port connection")
  , ("SE-142", "duplicate field in struct definition")
  , ("SE-143", "duplicate variant in enum definition")
  , ("SE-144", "duplicate procedure in interface definition")
  , ("SE-145", "loop between member function calls in class definition")
  , ("SE-146", "invalid type for dereference")
  , ("SE-147", "invalid type for match statement")
  , ("SE-148", "duplicate case in match statement")
  , ("SE-149", "unknown variant in match case")
  , ("SE-150", "missing case/s in match statement")
  , ("SE-151", "invalid type for is-variant expression")
  , ("SE-152", "invalid type for is-option-variant expression")
  , ("SE-153", "type mismatch in is-variant expression")
  , ("SE-154", "invalid procedure in outbound port")
  , ("SE-155", "invalid pool initialization")
  , ("SE-156", "invalid message queue initialization")
  , ("SE-157", "unknown global object")
  , ("SE-158", "invalid interrupt emitter type")
  , ("SE-159", "invalid periodic timer emitter type")
  , ("SE-160", "invalid system init emitter type")
  , ("SE-161", "message queue type mismatch")
  , ("SE-162", "message queue type mismatch")
  , ("SE-163", "pool type mismatch")
  , ("SE-164", "invalid task type")
  , ("SE-165", "invalid handler type")
  , ("SE-166", "invalid resource type")
  , ("SE-167", "invalid emitter type")
  , ("SE-168", "invalid channel type")
  , ("SE-169", "emitter class is not instantiable")
  , ("SE-170", "single expression type is not unit")
  , ("SE-171", "interface extends the same interface multiple times")
  , ("SE-172", "procedure duplicated in extended interfaces")
  , ("SE-173", "interface procedure previously defined by an extended interface")
  , ("SE-174", "interface previously extended by another interface")
  , ("SE-175", "resource provides the same interface multiple times")
  , ("SE-176", "procedure duplicated in provided interfaces")
  , ("SE-177", "interface previously extended by another interface")
  , ("SE-178", "invalid use of a string initializer")
  , ("SE-180", "assignment of a string array initializer to an invalid type")
  , ("SE-181", "invalid type for constant")
  , ("SE-182", "invalid access to a constant expression")
  , ("SE-183", "invalid type for result")
  , ("SE-184", "invalid type for status")
  , ("SE-185", "invalid variant for option")
  , ("SE-186", "invalid variant for result")
  , ("SE-187", "invalid variant for status")
  , ("SE-188", "invalid type specifier for result")
  , ("SE-189", "monadic variant parameter type mismatch")
  , ("SE-190", "object previously moved")
  , ("SE-191", "invalid type for is-status-variant expression")
  , ("SE-192", "invalid type for is-result-variant expression")
  , ("SE-193", "invalid system exception emitter type")
  , ("SE-194", "invalid interrupt action return type")
  , ("SE-195", "invalid periodic timer action return type")
  , ("SE-196", "invalid system init action return type")
  , ("SE-197", "invalid system exception action return type")
  , ("SE-198", "invalid message queue action return type")
  , ("SE-199", "type not in scope")
  , ("SE-200", "function not in scope")
  , ("SE-201", "unknown action")
  , ("SE-202", "in port action parameter type mismatch")
  , ("SE-203", "sink port action parameter type mismatch")
  , ("SE-204", "invalid viewer parameter type")
  , ("SE-205", "invalid access to procedure from immutable self reference")
  , ("SE-206", "invalid access to out port from immutable self reference")
  , ("SE-207", "self reference access kind mismatch in procedure")
  , ("SE-208", "task class defines a method")
  , ("SE-209", "handler class defines a method")
  , ("SE-210", "resource class defines a viewer")
  , ("SE-211", "unprotected resource with regular fields")
  , ("SE-212", "mutable member function in task class")
  , ("SE-213", "mutable member function in handler class")
  , ("SE-214", "binary operation expected result type not integer")
  , ("SE-215", "binary operation expected integer type on the left")
  , ("SE-216", "binary operation expected integer type on the right")
  ]

spec :: Spec
spec = do
  files <- runIO $ do
    entries <- listDirectory fixturesDir
    return $ sort [ f | f <- entries, "SE-" `isPrefixOf` f, ".fin" `isSuffixOf` f ]
  describe "Semantic: SE error-code coverage (one fixture per code)" $
    forM_ files $ \f -> do
      let code = dropExtension f
          name = maybe code (\t -> code ++ ": " ++ t) (lookup code titles)
      case lookup code shadowed of
        Just actual ->
          it name $ pendingWith ("currently shadowed: yields " ++ actual)
        Nothing ->
          it name $ do
            src <- readFile (fixturesDir </> f)
            compileErrorCode src `shouldBe` Just (pack code)

  multiCases <- runIO $ do
    subdirs <- sort . filter ("SE-" `isPrefixOf`) <$> listDirectory multiDir
    forM subdirs $ \d -> do
      fs <- sort . filter (".fin" `isSuffixOf`) <$> listDirectory (multiDir </> d)
      mods <- forM fs $ \f -> do
        src <- readFile (multiDir </> d </> f)
        return (dropExtension f, src)
      return (d, mods)
  describe "Semantic: multi-module SE error-code coverage" $
    forM_ multiCases $ \(code, mods) -> do
      let name = maybe code (\t -> code ++ ": " ++ t) (lookup code titles)
      it name $ compileProjectErrorCode mods `shouldBe` Just (pack code)
